MILD_ALARM_SOUND_PATH = "mild_alarm.wav"
FATIGUE_ALARM_SOUND_PATH = "alarm.wav"
STOP_ALARM_KEY = ord('s')

EMERGENCY_COUNTDOWN_SEC = 30
EMERGENCY_CONTACT_NAME = "Family Member"

import os
from dotenv import load_dotenv
load_dotenv()

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_WHATSAPP_FROM = os.getenv("TWILIO_WHATSAPP_FROM", "")

EMERGENCY_WHATSAPP_NUMBERS = [
    os.getenv("EMERGENCY_WHATSAPP_1", ""),
    os.getenv("EMERGENCY_WHATSAPP_2", ""),
    os.getenv("EMERGENCY_WHATSAPP_3", ""),
    os.getenv("EMERGENCY_WHATSAPP_4", ""),
]

EMERGENCY_POLICE = "100"
EMERGENCY_AMBULANCE = "108"

MODEL_PATH = "face_landmarker.task"
CAMERA_INDEX = 0
WINDOW_NAME = "Professional Fatigue Detection System"

SAVE_TO_CSV = True
CSV_FILE = "fatigue_features_log.csv"

SUMMARY_INTERVAL = 8.0
MAX_FACES = 1
DRAW_LANDMARKS = True

CONTINUOUS_EYE_CLOSURE_FATIGUE_SEC = 5.0

CAM_W = 960
CAM_H = 720
PANEL_W = 470
WINDOW_W = CAM_W + PANEL_W
WINDOW_H = CAM_H

EAR_CLOSED_THRESHOLD = 0.23
MAR_YAWN_THRESHOLD = 0.65

BLINK_CONSEC_FRAMES = 2
YAWN_CONSEC_FRAMES = 8

HEAD_NOD_DROP_THRESHOLD = 8.0
HEAD_NOD_CONSEC_FRAMES = 3

LEFT_EYE_IDX = [33, 160, 158, 133, 153, 144]
RIGHT_EYE_IDX = [362, 385, 387, 263, 373, 380]
MOUTH_IDX = [61, 81, 13, 311, 291, 402, 14, 178]

LEFT_EYE_OUTER = 33
RIGHT_EYE_OUTER = 263
FOREHEAD_IDX = 10
CHIN_IDX = 152